name: BVTest
favicon: null
layout_spectrum: 0.5012
typography_spectrum: 0.7515
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3372b7'
    - '#b8d3f0'
    - '#2386c9'
    - '#8ecabe'
    - '#58a5db'
  brandStrength: 0.948832182213664
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
