name: BVTest
favicon: null
layout_spectrum: 0.9201939816121012
typography_spectrum: 0.5789848521817476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.948832182213664
  lightness: 0.986230727750808
  saturation: 0.4866070996504277
  rhythmicContrast: 0.9676397433504462
purpose: []
